### ISSUE TITLE
Implementierung Imkerregistration

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#12]
# User Story
Als *Imker* möchte ich mich im «Beefinder» registrieren können, damit ich benachrichtigt werden kann, wenn in meiner geografischen Nähe ein Bienenschwarm gemeldet wird.

# Akzeptanzkriterien
- [x] Als Imker steht mir die Funktion «Als Imker Registrieren» zur Verfügung
- [x] Betätige ich die Funktion, so gelange ich auf die Registrationsseite, wo ich meine Details erfassen kann.
- [x] Folgende Details kann ich erfassen:
  - Name
  - Adresse
  - PLZ/Ort
  - E-Mail
- [x] Die Seite stellt die Funktion «Registrieren» zur Verfügung.
- [x] Betätige ich diese Funktion, so werden meine eingegebenen Angaben übermittelt und ich werde im System als Imker gespeichert.
- [x] Zudem wird **mindestens** die E-Mail-Adresse auf eine gültige Syntax überprüft.
- [ ] (**kann**) Falls die E-Mail vorgängig bereits verwendet wurde, wird eine entsprechende Fehlermeldung ausgegeben und die Funktion «Registrieren» wird nicht ausgeführt.
- [x] Hat die E-Mail-Adresse ein ungültige Syntax, kann ich die Funktion «Registrieren» nicht ausführen.
- [x] Habe ich die Funktion «Registrieren» ausgeführt, so wird mir das mit einer entsprechenden Meldung bestätigt. 

# Diskussion
- Wie soll Ermittlung der Position der Imker-«Homebase» umgesetzt werden? Aktueller Standort zum Registrierungszeitpunkt? Geocoding/Adresse? Eingabe Koordinaten?

**Comment by openscript** [comment]
Dieser Issue hat eine Verbindung mit #2.
