### ISSUE TITLE
Manueller Test: Bienenschwarm-Formular

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#13]
# Beschreibung
Für das Bienenschwarm-Formular (#10) wird manuell getestet, ob die Funktion intuitiv, d.h. ohne weitere Anleitung von den Testpersonen verstanden wird und angewendet werden kann. 

# Testpersonen
* Min. 1 Vertreter aus der Gruppe «Naturfreund»

# Ablauf
1. Der Testperson wird ein Smartphone zur Verfügung gestellt, auf dem «Beefinder» installiert ist (alternativ kann die Testperson auch dazu angeleitet werden, die App bei sich auf dem persönlichen Smartphone zu installieren)
2. Der Testperson wird vermittelt, dass sich in ihrer Nähe ein Bienenschwarm an einem Ast eines Baumes befindet.
3. Die Testperson wird damit beauftragt, diesen Bienenschwarm mit «Beefinder» zu erfassen und zu melden.

# Erwartete Erkenntnisse
* Findet die Testperson ihren Weg zum Bienenschwarm-Assistenten?
* Versteht die Testperson, wie sie einen Bienenschwarm vollständig erfassen und übermitteln kann?
* Versteht die Testperson, wozu die Angabe der persönlichen Daten getätigt werden kann?
* Versteht die Testperson, dass die Angabe der persönlichen Daten optional ist und übersprungen werden kann?

**Comment by aschorro** [comment]
Current status:
-Tested with current productive app version with product idea provider on laptop computer. Results will be documented in Google Doc.
-Testing with 'Naturfreund' on mobile phone is still pending.

**Comment by aschorro** [comment]
-Tested with beekeeper (idea provider) and 'Naturfreund'.
-Results documented in project documentation (Google doc).
