### ISSUE TITLE
Manueller Test: Imkerformular

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#14]
# Beschreibung
Für das Imker-Formular (#12) wird manuell getestet, ob die Funktion intuitiv, d.h. ohne weitere Anleitung von den Testpersonen verstanden wird und angewendet werden kann. 

# Testpersonen
* Min. 1 Vertreter aus der Gruppe «Imker» oder einer der ideengebenden Stakeholder

# Ablauf
1. Der Testperson wird ein Smartphone zur Verfügung gestellt, auf dem «Beefinder» installiert ist (alternativ kann die Testperson auch dazu angeleitet werden, die App bei sich auf dem persönlichen Smartphone zu installieren)
2. Der Testperson wird der Auftrag gegeben, sich bei «Beefinder» als Imker zu registrieren, damit sie über Bienenschwarmfunde informiert werden kann.

# Erwartete Erkenntnisse
* Findet die Testperson ihren Weg zum Registrations-Formular?
* Versteht die Testperson, wie sie sich als Imker registrieren kann?

**Comment by aschorro** [comment]
-Tested with beekeeper (idea provider) and 'Naturfreund'.
-Results documented in project documentation (Google doc).
