### ISSUE TITLE
Manueller Test: Imkerbenachrichtigung / Beanspruchung Bienenschwarm

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#15]
# Beschreibung
Für die Bienenschwarm-Benachrichtigung (#11) wird manuell getestet, ob die Funktion intuitiv, d.h. ohne weitere Anleitung von den Testpersonen verstanden wird und angewendet werden kann. 

# Testpersonen
* Min. 1 Vertreter aus der Gruppe «Imker» oder Ideengeber

# Ablauf
1. Der Testperson wird ein Smartphone zur Verfügung gestellt, auf dem «Beefinder» installiert ist (alternativ kann die Testperson auch dazu angeleitet werden, die App bei sich auf dem persönlichen Smartphone zu installieren)
2. Der Testperson wird vermittelt, dass sie als Imker bereits registriert sei.
3. Die Testperson wird damit beauftragt, auf einen Bienenschwarmfund bzw. eine Benachrichtigung zu warten.
4. Nachdem sie die Benachrichtigung erhalten hat, soll sie den Bienenschwarm für sich beanspruchen.

# Erwartete Erkenntnisse
* Findet die Testperson ihren Weg zur Bienenschwarm-Übersichtsseite?
* Versteht die Testperson, wie sie einen Bienenschwarm beanspruchen kann?
* Versteht die Testperson, was nach der Beanspruchung zu tun ist (Bienenschwarm einfangen)?

**Comment by aschorro** [comment]
-Tested with beekeeper (idea provider) and 'Naturfreund'.
-Results documented in project documentation (Google doc).
