### ISSUE TITLE
Vorbereitung Pitch

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#17]
Erstellen & Besprechen der Präsentation

**Comment by openscript** [comment]
@samuelblattner @aschorro @DimiTs 
Was ist genau der Ablauf?
Wir machen zuerst einen Pitch, um das Problem und die Idee vorzustellen.
Danach kommt noch eine Präsentation mit folgenden Inhalten:
1. Ausgangslage
1. Planung
1. Entscheidungen
1. Realisation
1. Arbeitsweise
1. Auswertung
1. Demonstration

Wie seht ihr das?

**Comment by aschorro** [comment]
Finde ich gut!
![Bienenvoelkerverteilung CH 2003](https://user-images.githubusercontent.com/36139738/58628827-08499700-82db-11e9-8cf9-1ebdc0966300.png)
[Statistische Angaben für Pitch-Präsi.txt](https://github.com/openscript/beefindr/files/3236690/Statistische.Angaben.fur.Pitch-Prasi.txt)
Anbei noch statistische Angaben und interessante Links für Pitch und Präsi.

**Comment by samuelblattner** [comment]
Falls die klassische Präsentationsform nach Modulplan und eurer Meinung nicht zwingend gefordert wird, würde ich das kippen und voll auf die Karte Pitch & Verkauf setzen, also z.B.:
1. «Gemäss Studie soundso werden pro Jahr soundso viele Bienenvölker gemeldet» (Ausgangslage)
2. «Bienenvölker sind für Imker von grossem Wert» (Chance)
3. «Problem sind lange und langsame Meldewege» (Problem)
4. «Wir haben eine Lösung entwickelt, die Melder und Imker direkt verbindet und das Potenzial hat, Bienen zu retten und Imker leichter zu Völkern zu bringen» (Lösung)
5. --- Theater Intermezzo --- «Huch, ein Bienenschwarm», erfasst Bienenschwarm mit App, App wird auf Leinwand gezeigt. Imker: «Huch, eine neue Bienenschwarmmeldung, schnell Annehmen!», App wird ebenfalls auf Leinwand gezeigt. Zieht Imkerausrüstung an und rennt aus raum.
6. «Unsere app ist als PWA umgesetzt und kann mit Firebase leicht skaliert werden (oder irgendwie sowas»
7. Optional: «Für die Monetarisierung stellen wir uns eine Provision von 40.-/pro vermitteltem Bienenschwarm vor»
8 ... etc
