### ISSUE TITLE
Applikationstitel auf Startseite verlinken

### ISSUE THREAD

**Issue by openscript** [openscript/beefindr#23]
Es geht darum, dass wenn der Applikationstitel angeklickt/berührt wird, eine Weiterleitung auf die Startseite `/` der App erfolgt.

![image](https://user-images.githubusercontent.com/1105080/57176957-108aef80-6e5f-11e9-92dc-fdf9dab48de8.png)

## Akzeptanzkriterien
- [x] Als Benutzer möchte ich auf die Startseite weitergeleitet werden, wenn ich auf den Titel klicke.

**Comment by aschorro** [comment]
Implemented and tested within branch features/#23Applikationstitel. Merged into master.
