### ISSUE TITLE
Feedback User-Tests: Finder kann seine Mobile-Tel.-Nr. angeben

### ISSUE THREAD

**Issue by aschorro** [openscript/beefindr#46]
## Durchgeführter manueller Test
Issue: [#13 Bienenschwarm-Formular](https://github.com/openscript/beefindr/issues/13)

## Feedback

- [x] Finder kann mit seinen (fakultativen) Daten auch seine Mobile-Tel.-Nr. mitsenden.

**Comment by openscript** [comment]
Dazu könnte https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel verwendet werden.
