### ISSUE TITLE
Feedback User-Tests: Finder erhält motivierenden Benutzungshinweis

### ISSUE THREAD

**Issue by aschorro** [openscript/beefindr#47]
## Durchgeführter manueller Test
Issue: [#13 Bienenschwarm-Formular](https://github.com/openscript/beefindr/issues/13)

## Feedback

- [x] Finder erhält auf Startseite kurz und bündig eine motivierende Info darüber, dass die App-Nutzung/Teilnahme kostenlos ist.

## Vorschlag für Nutzungsslogan
![image](https://user-images.githubusercontent.com/36139738/58000790-1b3db980-7ada-11e9-9bbb-b831d3cdd049.png)

**Comment by samuelblattner** [comment]
Von mir aus könnte man das auch kürzen zu:

**Bienenschwarm finden & süss belohnt werden!**

oder 

**Bienenschwarm finden & Honig verdienen**

oder 

**Jeder Bienenschwarm ist Honig wert** (finde ich vom Rhythmus schöner, da 'Bienenschwarm' ein etwas sperriges Wort ist. Der Call to action ist dann im Button 'Jetzt Bienenschwarm melden')

**Comment by openscript** [comment]
1. **Bringen Sie Imker zu schwärmen**
2. **Helfen Sie mit ein schönes Zuhause für Bienchen zu finden**

**Comment by aschorro** [comment]
Das sind alles gute Folge-Vorschläge. Bei jedem fehlen aber zwei wichtige Botschaften:

- **Das Melden eines Schwarmes ist kostenlos.** Die App wird nur erfolgreich sein, wenn die Schwelle zur Nutzung ganz niedrig ist. Das Wissen um die kostenlose Teilnahme trägt wesentlich dazu bei.

- **Eine Belohnung ist nicht garantiert.** Der App-Betreiber kann weder versprechen, dass eine Meldung vom ausgewählten Imker belohnt wird, noch kann der Betreiber das kontrollieren. Hinzu kommt, dass ein Schwarm trotz Meldung evtl. nicht eingefangen werden kann, da er beim Eintreffen des Imkers schon weggezogen ist, oder weil er am Ende dann doch an einer unzugänglichen Stelle gesichtet wurde.

Ich schlage vor, für das MVP die ursprüngliche Variante zu nehmen. Sie kann bei Weiterverwendung der App immer noch abgeändert werden.

**Comment by openscript** [comment]
Hört sich gut an! Dann so einbauen :1st_place_medal:
