### ISSUE TITLE
Feedback User-Tests: Imkerregistration funktioniert nicht unter Android V8.0 Oreo / Beefindr-dev

### ISSUE THREAD

**Issue by aschorro** [openscript/beefindr#62]
## Durchgeführter manueller Test
Issue: [#14 Imkerformular](https://github.com/openscript/beefindr/issues/14)

Getestet auf Samsung Galaxy S7 Android V8.0 Oreo mit Beefindr-dev

## Problem

- Imker-Registrierung wird nach Ausfüllen und Absenden des Formulars mit Pop-up unten bestätigt.
- Formular bleibt in gleichem, ausgefülltem Zustand geöffnet und kann immer wieder erneut gesendet werden (mit weiteren Pop-up-Bestätigungen).
- Es werden jedoch nicht alle Daten an die DB übermittelt (z.B. fehlen Strasse, Ort, etc.)
- Bei einer zweiten Anmeldung konnte derselbe Effekt beobachtet/reproduziert werden.
Siehe DB-Einträge bzw. Screenshots unten.

## Folgemassnahme

- [ ] Bugfix der Imker-Registrierung umsetzen.

![image](https://user-images.githubusercontent.com/36139738/58727923-f7d21300-83e5-11e9-9cba-f099dc76bab0.png)
![image](https://user-images.githubusercontent.com/36139738/58727967-0d473d00-83e6-11e9-92b5-e3d969a94644.png)
![image](https://user-images.githubusercontent.com/36139738/58727992-1e904980-83e6-11e9-802e-029b33bdbf02.png)
![image](https://user-images.githubusercontent.com/36139738/58728017-34057380-83e6-11e9-8526-c800ef73b164.png)
![image](https://user-images.githubusercontent.com/36139738/58728064-539c9c00-83e6-11e9-8f0b-038bb66c0097.png)

**Comment by openscript** [comment]
Solved with #63
