### ISSUE TITLE
Risikoanalyse

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#7]
# Ziel
Schutzbedarf und Risikoanalyse erstellen (die Excel Vorlagen verwenden)
# Auftrag
- [x] Schutzbedarf und Risikoanalyse erstellen (die Excel Vorlagen verwenden)
 https://www.isb.admin.ch/isb/de/home/ikt-vorgaben/prozesse-methoden/p041-schutzbedarfsanalyse_schuban.html
    https://www.isb.admin.ch/isb/de/home/ikt-vorgaben/prozesse-methoden/p042-informationssicherheits-und-datenschutzkonzept_ISDS.html
- [x] Auswahl der geeigneten Schutzmassnahmen
- [x] Konfigurieren der Massnahmen für den Service und das GUI umsetzen und testen
- [x] Dokumentation für den Schlussbericht erstellen
- [x] **Die 2 Top Risiken und 2 wichtigsten Massnahmen im Modulforum mit den anderen Gruppen teilen und gegenseitig kommentieren.**

**Comment by aschorro** [comment]
Security completely described in Google Docs for Beefinder.
