### ISSUE TITLE
PWA Fähigkeit erstellen

### ISSUE THREAD

**Issue by samuelblattner** [openscript/beefindr#9]
# User Story
Als *Naturfreund*/*Imker* möchte ich «Beefinder» auf meinem Smartphone installieren können (als pwa), sodass ich die App via Icon schnell und einfach starten kann und die Applikation nicht mühsam über eine Browser/Internetadresse öffnen muss.

# Akzeptanzkriterien
- [x] Wenn ich die Einstiegsseite über den Browser erstmalig aufrufe, steht mir die Funktion «App installieren/zum Home-Screen hinzufügen (o.ä.)» zur Verfügung
- [x] Betätige ich diese Funktion, wird die App auf meinem Smartphone installiert.
- [x] Die App wird auf meinem Smartphone mit dem «Beefinder»-Logo dargestellt.
- [x] Das Label der App lautet auf meinem Smartphone «Beefinder»
- [x] Öffne ich die App über das Icon, wird die Browseradresszeile in der App nicht mehr dargestellt (im Gegensatz zu wenn ich die Seite direkt im Browser öffne)
- [x] Das Logo als FavIcon definieren

**Comment by openscript** [comment]
Was man hier noch machen könnte ist ein FavIcon zu setzen:
![image](https://user-images.githubusercontent.com/1105080/57176697-55148c00-6e5b-11e9-9958-889a93d8cc2b.png)

**Comment by openscript** [comment]
![image](https://user-images.githubusercontent.com/1105080/57183407-fe37a280-6eac-11e9-81fd-6f58bf41dbee.png)
